package com.odeyalo.sonata.cello.core.authentication.oauth2;

import com.odeyalo.sonata.cello.core.authentication.resourceowner.AuthenticationCredentials;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Value;
import org.jetbrains.annotations.NotNull;

/**
 * Represents the credentials required for OAuth 2.0 authentication using the Authorization Code Grant flow.
 * <p>
 * In this stage, the user has already been authenticated by the OAuth 2.0 provider and redirected to the specified
 * redirect URI. An authorization code has been generated by the Oauth 2.0 Provider and included in redirect uri.
 */
@Value
@AllArgsConstructor
@Builder
public class Oauth2ProviderAuthorizationCodeAuthenticationCredentials implements AuthenticationCredentials {

    /**
     * The name of the OAuth 2.0 provider where the user entered their credentials.
     */
    @NotNull
    String providerName;

    /**
     * The authorization code generated by the OAuth 2.0 server. This code will be exchanged for an access token.
     */
    @NotNull
    String authorizationCode;
}
