package com.odeyalo.sonata.cello.core.responsetype.code;

import org.jetbrains.annotations.NotNull;
import org.springframework.util.Assert;

/**
 * Represent an authorization code generated by Sonata, that can be used to exchange it to access token
 * @param value - authorization code value
 */
public record GeneratedAuthorizationCode(@NotNull String value) {

    public GeneratedAuthorizationCode {
        Assert.state(value.length() >= 5, () -> "An authorization code must be greater or equal to 5 characters!");
    }

    public static GeneratedAuthorizationCode wrapString(final String value) {
        return new GeneratedAuthorizationCode(value);
    }
}
