package com.odeyalo.sonata.cello.core.responsetype.code;

import lombok.Builder;
import lombok.Value;
import org.jetbrains.annotations.NotNull;

/**
 * Represent an authorization code generated by Sonata, that can be used to exchange it to access token
 */
@Value
@Builder
public class GeneratedAuthorizationCode {
    @NotNull
    String codeValue;
    @NotNull
    AuthorizationCodeMetadata metadata;
}
